'use client';

import React, { useEffect, useState, Suspense } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { DashboardLayout } from '@/components/layout/dashboard-layout';
import { motion } from 'framer-motion';
import { BookOpen, Calendar, Trash2, ChevronRight, Loader2 } from 'lucide-react';
import { useAuth } from '@/contexts/auth-context';
import { getCurricula, deleteCurriculum } from '@/lib/firestore';

interface SavedCurriculum {
  id: string;
  field: string;
  domain?: string;
  createdAt: string;
  modules: any[];
}

// Wrapper to handle Suspense requirement for useSearchParams
export default function LearningPathsPageWrapper() {
  return (
    <Suspense fallback={
      <DashboardLayout>
        <div className="flex items-center justify-center min-h-[400px]">
          <Loader2 className="h-8 w-8 animate-spin text-blue-500" />
        </div>
      </DashboardLayout>
    }>
      <LearningPathsPage />
    </Suspense>
  );
}

function LearningPathsPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const domainFilter = searchParams.get('domain');
  const { user } = useAuth();

  const [curricula, setCurricula] = useState<SavedCurriculum[]>([]);
  const [loading, setLoading] = useState(true);
  const [showMigrationBanner, setShowMigrationBanner] = useState(false);

  useEffect(() => {
    const loadCurricula = async () => {
      if (!user) {
        setLoading(false);
        return;
      }

      try {
        const data = await getCurricula(user.uid);

        // Filter by domain if specified
        const filtered = domainFilter
          ? data.filter((c: SavedCurriculum) => (c.domain || 'technology') === domainFilter)
          : data;

        setCurricula(filtered.reverse()); // Most recent first
      } catch (e) {
        console.error('Failed to load curricula', e);
      } finally {
        setLoading(false);
      }
    };

    loadCurricula();
  }, [user, domainFilter]);

  const migrateDomains = () => {
    const curricula = JSON.parse(localStorage.getItem('curricula') || '[]');

    const updated = curricula.map((curriculum: any) => {
      if (curriculum.domain) return curriculum;

      const field = curriculum.field.toLowerCase();
      let domain = 'other';

      if (field.includes('sql') || field.includes('machine learning') || field.includes('ml') ||
        field.includes('programming') || field.includes('tech') || field.includes('data')) {
        domain = 'technology';
      } else if (field.includes('finance') || field.includes('trading') || field.includes('money')) {
        domain = 'finance';
      } else if (field.includes('business') || field.includes('management') || field.includes('marketing')) {
        domain = 'business';
      } else if (field.includes('biology') || field.includes('chemistry') || field.includes('physics') ||
        field.includes('science') || field.includes('molecular')) {
        domain = 'sciences';
      } else if (field.includes('art') || field.includes('design') || field.includes('music')) {
        domain = 'arts';
      }

      return { ...curriculum, domain };
    });

    localStorage.setItem('curricula', JSON.stringify(updated));
    localStorage.setItem('domains-migrated', 'true');
    setShowMigrationBanner(false);
    window.location.reload();
  };

  const handleDelete = async (id: string) => {
    if (!user) return;

    try {
      await deleteCurriculum(user.uid, id);
      // Refresh list
      const data = await getCurricula(user.uid);
      const filtered = domainFilter
        ? data.filter((c: SavedCurriculum) => (c.domain || 'technology') === domainFilter)
        : data;
      setCurricula(filtered.reverse());
    } catch (e) {
      console.error('Failed to delete curriculum', e);
    }
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  return (
    <DashboardLayout>
      <div className="max-w-4xl mx-auto">
        <div className="mb-8 flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold text-white mb-2">Learning Paths</h1>
            <p className="text-slate-400">
              Your personalized curricula generated by AI
            </p>
          </div>
          <button
            onClick={() => router.push('/learning-paths/create')}
            className="px-4 py-2 rounded-lg bg-blue-500 hover:bg-blue-600 text-white font-medium transition-colors"
          >
            + Create Manual
          </button>
        </div>

        {/* Migration Banner */}
        {showMigrationBanner && (
          <div className="mb-6 p-4 rounded-lg bg-blue-500/10 border border-blue-500/30">
            <div className="flex items-start justify-between gap-4">
              <div className="flex-1">
                <h3 className="font-semibold text-white mb-1">🔧 Domain Migration Available</h3>
                <p className="text-sm text-slate-300 mb-3">
                  Your curricula don't have domains assigned. Click below to auto-categorize them!
                </p>
                <button
                  onClick={migrateDomains}
                  className="px-4 py-2 rounded-lg bg-blue-500 hover:bg-blue-600 text-white font-medium text-sm transition-colors"
                >
                  Auto-Assign Domains
                </button>
              </div>
              <button
                onClick={() => {
                  localStorage.setItem('domains-migrated', 'true');
                  setShowMigrationBanner(false);
                }}
                className="text-slate-400 hover:text-white"
              >
                ✕
              </button>
            </div>
          </div>
        )}

        {curricula.length === 0 ? (
          <div className="card text-center py-16">
            <BookOpen className="h-16 w-16 text-slate-600 mx-auto mb-4" />
            <h2 className="text-xl font-semibold text-white mb-2">No Learning Paths Yet</h2>
            <p className="text-slate-400 mb-6">
              Generate your first curriculum from the dashboard
            </p>
            <button
              onClick={() => router.push('/dashboard')}
              className="px-6 py-2 rounded-lg bg-blue-500 hover:bg-blue-600 text-white font-medium transition-colors"
            >
              Go to Dashboard
            </button>
          </div>
        ) : (
          <div className="space-y-4">
            {curricula.map((curriculum, index) => (
              <motion.div
                key={curriculum.id}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.05 }}
                className="card-hover group"
                onClick={() => router.push(`/learning-paths/${curriculum.id}`)}
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-4 flex-1">
                    <div className="h-12 w-12 rounded-lg bg-gradient-to-br from-blue-500 to-purple-500 flex items-center justify-center">
                      <BookOpen className="h-6 w-6 text-white" />
                    </div>
                    <div className="flex-1">
                      <h3 className="text-lg font-semibold text-white group-hover:text-blue-400 transition-colors">
                        {curriculum.field}
                      </h3>
                      <div className="flex items-center gap-4 mt-1">
                        <div className="flex items-center gap-1 text-sm text-slate-400">
                          <Calendar className="h-4 w-4" />
                          {formatDate(curriculum.createdAt)}
                        </div>
                        <div className="text-sm text-slate-500">
                          {curriculum.modules?.length || 0} modules
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className="flex items-center gap-2">
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        if (confirm('Delete this curriculum?')) {
                          handleDelete(curriculum.id);
                        }
                      }}
                      className="p-2 rounded-lg hover:bg-red-500/10 text-slate-400 hover:text-red-400 transition-colors"
                    >
                      <Trash2 className="h-5 w-5" />
                    </button>
                    <ChevronRight className="h-5 w-5 text-slate-600 group-hover:text-blue-400 transition-colors" />
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        )}
      </div>
    </DashboardLayout>
  );
}
