'use client';

import React, { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { motion, AnimatePresence } from 'framer-motion';
import {
    ChevronDown,
    ChevronRight,
    BookOpen,
    PlayCircle,
    FileText,
    Clock,
    CheckCircle,
    Brain,
    ArrowLeft
} from 'lucide-react';
import { DashboardLayout } from '@/components/layout/dashboard-layout';
import type { Module, Topic, Lesson } from '@/types/curriculum';

export default function CurriculumViewPage() {
    const router = useRouter();
    const [curriculum, setCurriculum] = useState<any>(null);
    const [expandedModules, setExpandedModules] = useState<Record<string, boolean>>({});
    const [expandedTopics, setExpandedTopics] = useState<Record<string, boolean>>({});

    useEffect(() => {
        const saved = localStorage.getItem('currentCurriculum');
        if (!saved) {
            router.push('/dashboard');
            return;
        }
        try {
            const parsed = JSON.parse(saved);
            setCurriculum(parsed);
            // Expand first module by default
            if (parsed.modules && parsed.modules.length > 0) {
                setExpandedModules({ [parsed.modules[0].id]: true });
            }
        } catch (e) {
            console.error('Failed to parse curriculum', e);
        }
    }, [router]);

    if (!curriculum) {
        return (
            <DashboardLayout>
                <div className="flex h-96 items-center justify-center">
                    <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-500"></div>
                </div>
            </DashboardLayout>
        );
    }

    const toggleModule = (id: string) => {
        setExpandedModules(prev => ({ ...prev, [id]: !prev[id] }));
    };

    const toggleTopic = (id: string) => {
        setExpandedTopics(prev => ({ ...prev, [id]: !prev[id] }));
    };

    return (
        <DashboardLayout>
            <div className="max-w-4xl mx-auto space-y-8">
                {/* Header */}
                <div className="flex items-center gap-4">
                    <button
                        onClick={() => router.back()}
                        className="p-2 rounded-lg bg-slate-800/50 hover:bg-slate-800 text-slate-400 hover:text-white transition-colors"
                    >
                        <ArrowLeft className="h-5 w-5" />
                    </button>
                    <div>
                        <h1 className="text-3xl font-bold text-white mb-1">
                            {curriculum.field} Curriculum
                        </h1>
                        <p className="text-slate-400">
                            Personalized mastery path generated by AI
                        </p>
                    </div>
                </div>

                {/* Modules List */}
                <div className="space-y-4">
                    {curriculum.modules.map((module: Module) => (
                        <div
                            key={module.id}
                            className="rounded-xl border border-blue-500/20 bg-slate-900/50 overflow-hidden"
                        >
                            {/* Module Header */}
                            <button
                                onClick={() => toggleModule(module.id)}
                                className="w-full flex items-center justify-between p-6 hover:bg-slate-800/30 transition-colors text-left"
                            >
                                <div className="flex items-center gap-4">
                                    <div className="h-10 w-10 rounded-lg bg-blue-500/10 flex items-center justify-center text-blue-400">
                                        <BookOpen className="h-6 w-6" />
                                    </div>
                                    <div>
                                        <h2 className="text-xl font-semibold text-white">{module.name}</h2>
                                        <p className="text-sm text-slate-400">{module.description}</p>
                                    </div>
                                </div>
                                {expandedModules[module.id] ? (
                                    <ChevronDown className="h-5 w-5 text-slate-400" />
                                ) : (
                                    <ChevronRight className="h-5 w-5 text-slate-400" />
                                )}
                            </button>

                            {/* Topics */}
                            <AnimatePresence>
                                {expandedModules[module.id] && (
                                    <motion.div
                                        initial={{ height: 0, opacity: 0 }}
                                        animate={{ height: 'auto', opacity: 1 }}
                                        exit={{ height: 0, opacity: 0 }}
                                        className="border-t border-blue-500/10 bg-slate-900/30"
                                    >
                                        <div className="p-4 space-y-3">
                                            {module.topics.map((topic: Topic) => (
                                                <div key={topic.id} className="rounded-lg border border-slate-700/50 bg-slate-800/20">
                                                    {/* Topic Header */}
                                                    <button
                                                        onClick={() => toggleTopic(topic.id)}
                                                        className="w-full flex items-center justify-between p-4 hover:bg-slate-800/50 transition-colors"
                                                    >
                                                        <span className="font-medium text-slate-200">{topic.name}</span>
                                                        {expandedTopics[topic.id] ? (
                                                            <ChevronDown className="h-4 w-4 text-slate-500" />
                                                        ) : (
                                                            <ChevronRight className="h-4 w-4 text-slate-500" />
                                                        )}
                                                    </button>

                                                    {/* Lessons */}
                                                    <AnimatePresence>
                                                        {expandedTopics[topic.id] && (
                                                            <motion.div
                                                                initial={{ height: 0 }}
                                                                animate={{ height: 'auto' }}
                                                                exit={{ height: 0 }}
                                                                className="px-4 pb-4 overflow-hidden"
                                                            >
                                                                <div className="space-y-2 pt-2 border-t border-slate-700/30">
                                                                    {topic.lessons.map((lesson: Lesson) => (
                                                                        <div
                                                                            key={lesson.id}
                                                                            className="flex items-center justify-between p-3 rounded-md bg-slate-900/40 border border-slate-800 hover:border-blue-500/30 transition-colors group cursor-pointer"
                                                                        >
                                                                            <div className="flex items-center gap-3">
                                                                                <PlayCircle className="h-4 w-4 text-blue-400 group-hover:text-blue-300" />
                                                                                <span className="text-sm text-slate-300 group-hover:text-white">
                                                                                    {lesson.name}
                                                                                </span>
                                                                            </div>
                                                                            <div className="flex items-center gap-3">
                                                                                <div className="flex items-center gap-1 text-xs text-slate-500">
                                                                                    <Clock className="h-3 w-3" />
                                                                                    {lesson.estimatedMinutes}m
                                                                                </div>
                                                                                <button className="text-xs px-2 py-1 rounded bg-blue-500/10 text-blue-400 hover:bg-blue-500/20 transition-colors font-medium">
                                                                                    Start
                                                                                </button>
                                                                            </div>
                                                                        </div>
                                                                    ))}
                                                                </div>
                                                            </motion.div>
                                                        )}
                                                    </AnimatePresence>
                                                </div>
                                            ))}
                                        </div>
                                    </motion.div>
                                )}
                            </AnimatePresence>
                        </div>
                    ))}
                </div>
            </div>
        </DashboardLayout>
    );
}
